language: cpp
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y ninja-build python3-setuptools zlib1g-dev
- sudo easy_install3 pip
- sudo pip3 install -q meson
script: "./scripts/cibuild"
branches:
  only:
  - "write-doc"
