sudo: required
dist: trusty
language: cpp
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y python3.4 python-virtualenv doxygen zlib1g-dev graphviz
script: "./scripts/cibuild"
branches:
  only:
  - "write-doc"
